services:
  db:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: scriptgestor
      MYSQL_USER: victor
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  springboot:
    build: .
    container_name: springboot-container
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/scriptgestor
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8080:8080"
    depends_on:
      - db


